# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go-Fortune

on:
  push:
    branches:
    - v[0-9]+.[0-9]+
    - "!v*.*-beta"
    - "!v*.*.*"

jobs:

  build_and_deploy:
  if: ${{ !startsWith(github.event.head_commit.message, '#NORUN') }}
  runs-on: ubuntu-latest
    steps:
     - name: Echo current branch
        run: echo “$(date):current branch is ${{ github.ref_name }}”
        
      - name: Checkout current branch 
        uses: actions/checkout@v3 
        with:
         ref: ${{ github.ref_name }}
         token: ${{ secrets.YOUR_GITHUB_TOKEN}}
     - name: Use Node 18
        uses: actions/setup-node@v3
        with:
        node-version: '18'
        
      - name: Login to RailWay
        run: railway login 

      - name: Link Railway Project
        run: railway link 

      - name: Deploy to railway
        run: railway up 
        env:
         RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      - name: Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
         tag_name: ${{ github.ref_name }}
         release_name: Release ${{ github.ref_name }}
         body: |
             Golang Release
              draft: false
              prerelease: false
         
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
           payload: |
            {
            "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
            "blocks": [
                {
                    "type": "header",
                    "text": {
                        "type": "plain_text",
                        "text": "DipSA55 CI/CD Assignment Submission",
                        "emoji": true
                    }
                },
                {
                    "type": "section",
                    "fields": [
                        {
                            "type": "mrkdwn",
                            "text": "*Name:*\n Jiang Bingyu"
                        },
                        {
                            "type": "mrkdwn",
                            "text": "*Metriculation:*\nA0265058Y"
                        }
                    ]
                },
                {
                    "type": "section",
                    "fields": [
                        {
                            "type": "mrkdwn",
                            "text": "*Email:*\ne1045733@u.nus.edu"
                        },
                        {
                            "type": "mrkdwn",
                            "text": "*Repositary:*\nhttps://github.com/jiang1007/GoFortune.git"
                        }
                    ]
                },
                {
                    "type": "section",
                    "fields": [
                        {
                            "type": "mrkdwn",
                            "text": "*Delopyment:*\nhttps://go-fortune-production-3859.up.railway.app/"
                        }
                    ]
                },
                {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "<https://golang-production-96ca.up.railway.app/|Open Application>"
                    }
                }
            ]

            }
        env:
         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL1 }}
         SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
         
     
        
         
         
